name             'zip_mesos'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_mesos'
long_description 'Installs/Configures zip_mesos'
version          '0.1.2'

depends 'docker'
depends 'mesos'
